//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trophic.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trophic.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Trophic.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to At timestamp....
        /// </summary>
        public static string AtTimestamp {
            get {
                return ResourceManager.GetString("AtTimestamp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add profile.
        /// </summary>
        public static string AutoAddProfile {
            get {
                return ResourceManager.GetString("AutoAddProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bronze.
        /// </summary>
        public static string AutoBronze {
            get {
                return ResourceManager.GetString("AutoBronze", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bronze trophy count.
        /// </summary>
        public static string AutoBronzeCount {
            get {
                return ResourceManager.GetString("AutoBronzeCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear all trophies including synced.
        /// </summary>
        public static string AutoClearIncludingSynced {
            get {
                return ResourceManager.GetString("AutoClearIncludingSynced", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear search.
        /// </summary>
        public static string AutoClearSearch {
            get {
                return ResourceManager.GetString("AutoClearSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string AutoGold {
            get {
                return ResourceManager.GetString("AutoGold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gold trophy count.
        /// </summary>
        public static string AutoGoldCount {
            get {
                return ResourceManager.GetString("AutoGoldCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import timestamps from text file.
        /// </summary>
        public static string AutoImportFromFile {
            get {
                return ResourceManager.GetString("AutoImportFromFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import timestamps from website.
        /// </summary>
        public static string AutoImportFromWebsite {
            get {
                return ResourceManager.GetString("AutoImportFromWebsite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Platinum.
        /// </summary>
        public static string AutoPlatinum {
            get {
                return ResourceManager.GetString("AutoPlatinum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Platinum trophy count.
        /// </summary>
        public static string AutoPlatinumCount {
            get {
                return ResourceManager.GetString("AutoPlatinumCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile for resigning.
        /// </summary>
        public static string AutoProfileResigning {
            get {
                return ResourceManager.GetString("AutoProfileResigning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove selected profile.
        /// </summary>
        public static string AutoRemoveProfile {
            get {
                return ResourceManager.GetString("AutoRemoveProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search trophies.
        /// </summary>
        public static string AutoSearchTrophies {
            get {
                return ResourceManager.GetString("AutoSearchTrophies", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string AutoSilver {
            get {
                return ResourceManager.GetString("AutoSilver", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Silver trophy count.
        /// </summary>
        public static string AutoSilverCount {
            get {
                return ResourceManager.GetString("AutoSilverCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unlock all at specific timestamp.
        /// </summary>
        public static string AutoUnlockAtTimestamp {
            get {
                return ResourceManager.GetString("AutoUnlockAtTimestamp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unlock all with randomized timestamps.
        /// </summary>
        public static string AutoUnlockRandomized {
            get {
                return ResourceManager.GetString("AutoUnlockRandomized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear all (including synced).
        /// </summary>
        public static string ClearAllIncludingSynced {
            get {
                return ResourceManager.GetString("ClearAllIncludingSynced", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear filters.
        /// </summary>
        public static string ClearFilters {
            get {
                return ResourceManager.GetString("ClearFilters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear Selected.
        /// </summary>
        public static string ClearSelected {
            get {
                return ResourceManager.GetString("ClearSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string ColumnIcon {
            get {
                return ResourceManager.GetString("ColumnIcon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Trophy.
        /// </summary>
        public static string ColumnTrophy {
            get {
                return ResourceManager.GetString("ColumnTrophy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ColumnType {
            get {
                return ResourceManager.GetString("ColumnType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        public static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy Name.
        /// </summary>
        public static string CopyName {
            get {
                return ResourceManager.GetString("CopyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Day:.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Days:.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DST.
        /// </summary>
        public static string DST {
            get {
                return ResourceManager.GetString("DST", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Time....
        /// </summary>
        public static string EditTime {
            get {
                return ResourceManager.GetString("EditTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} Earned.
        /// </summary>
        public static string EarnedFormat {
            get {
                return ResourceManager.GetString("EarnedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to or press Ctrl+O to browse.
        /// </summary>
        public static string EmptyStateBrowse {
            get {
                return ResourceManager.GetString("EmptyStateBrowse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drop a trophy folder here to open it.
        /// </summary>
        public static string EmptyStateDrop {
            get {
                return ResourceManager.GetString("EmptyStateDrop", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Catalog {
            get { return ResourceManager.GetString("Catalog", resourceCulture); }
        }

        public static string TooltipCatalog {
            get { return ResourceManager.GetString("TooltipCatalog", resourceCulture); }
        }

        public static string CatalogTitle {
            get { return ResourceManager.GetString("CatalogTitle", resourceCulture); }
        }

        public static string CatalogSearchPlaceholder {
            get { return ResourceManager.GetString("CatalogSearchPlaceholder", resourceCulture); }
        }

        public static string CatalogResultCount {
            get { return ResourceManager.GetString("CatalogResultCount", resourceCulture); }
        }

        public static string CatalogDownloadOpen {
            get { return ResourceManager.GetString("CatalogDownloadOpen", resourceCulture); }
        }

        public static string CatalogDownloading {
            get { return ResourceManager.GetString("CatalogDownloading", resourceCulture); }
        }

        public static string CatalogSelectFolder {
            get { return ResourceManager.GetString("CatalogSelectFolder", resourceCulture); }
        }

        public static string CatalogDownloadFailed {
            get { return ResourceManager.GetString("CatalogDownloadFailed", resourceCulture); }
        }

        public static string CatalogNoResults {
            get { return ResourceManager.GetString("CatalogNoResults", resourceCulture); }
        }

        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EXP.
        /// </summary>
        public static string EXP {
            get {
                return ResourceManager.GetString("EXP", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} of {1}.
        /// </summary>
        public static string FilteredFormat {
            get {
                return ResourceManager.GetString("FilteredFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Earned.
        /// </summary>
        public static string FilterEarned {
            get {
                return ResourceManager.GetString("FilterEarned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        public static string FilterGold {
            get {
                return ResourceManager.GetString("FilterGold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bronze.
        /// </summary>
        public static string FilterBronze {
            get {
                return ResourceManager.GetString("FilterBronze", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string FilterLabel {
            get {
                return ResourceManager.GetString("FilterLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not Earned.
        /// </summary>
        public static string FilterNotEarned {
            get {
                return ResourceManager.GetString("FilterNotEarned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Platinum.
        /// </summary>
        public static string FilterPlatinum {
            get {
                return ResourceManager.GetString("FilterPlatinum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        public static string FilterSilver {
            get {
                return ResourceManager.GetString("FilterSilver", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Synced.
        /// </summary>
        public static string FilterSynced {
            get {
                return ResourceManager.GetString("FilterSynced", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fixed values.
        /// </summary>
        public static string FixedValues {
            get {
                return ResourceManager.GetString("FixedValues", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Override specific parts of every imported timestamp:.
        /// </summary>
        public static string FixedValuesDesc {
            get {
                return ResourceManager.GetString("FixedValuesDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only checked fields will be overridden. Unchecked fields keep their original values..
        /// </summary>
        public static string FixedValuesHint {
            get {
                return ResourceManager.GetString("FixedValuesHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From text file....
        /// </summary>
        public static string FromTextFile {
            get {
                return ResourceManager.GetString("FromTextFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Format: Trophy Name | YYYY-MM-DD HH:MM:SS ....
        /// </summary>
        public static string FromTextFileTooltip {
            get {
                return ResourceManager.GetString("FromTextFileTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From website....
        /// </summary>
        public static string FromWebsite {
            get {
                return ResourceManager.GetString("FromWebsite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Future dates cannot be synced to PSN and may flag your account..
        /// </summary>
        public static string FutureDateWarning {
            get {
                return ResourceManager.GetString("FutureDateWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hour:.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hour:.
        /// </summary>
        public static string HourLabel {
            get {
                return ResourceManager.GetString("HourLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hours:.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import as-is.
        /// </summary>
        public static string ImportAsIs {
            get {
                return ResourceManager.GetString("ImportAsIs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timestamps will be imported exactly as they appear on the source profile..
        /// </summary>
        public static string ImportAsIsDesc {
            get {
                return ResourceManager.GetString("ImportAsIsDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import Timestamps.
        /// </summary>
        public static string ImportTimestampsTitle {
            get {
                return ResourceManager.GetString("ImportTimestampsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL (https://...)..
        /// </summary>
        public static string InvalidUrlError {
            get {
                return ResourceManager.GetString("InvalidUrlError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lock Selected.
        /// </summary>
        public static string LockSelected {
            get {
                return ResourceManager.GetString("LockSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Min:.
        /// </summary>
        public static string MinLabel {
            get {
                return ResourceManager.GetString("MinLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minute:.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minutes:.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Month:.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Months:.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add or subtract time from all imported timestamps:.
        /// </summary>
        public static string OffsetDesc {
            get {
                return ResourceManager.GetString("OffsetDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use negative values to subtract (e.g. -2 years)..
        /// </summary>
        public static string OffsetHint {
            get {
                return ResourceManager.GetString("OffsetHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profile:.
        /// </summary>
        public static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Randomized.
        /// </summary>
        public static string Randomized {
            get {
                return ResourceManager.GetString("Randomized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sec:.
        /// </summary>
        public static string SecLabel {
            get {
                return ResourceManager.GetString("SecLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Second:.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Seconds:.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Date and Time.
        /// </summary>
        public static string SelectDateTimeTitle {
            get {
                return ResourceManager.GetString("SelectDateTimeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select trophy unlock date and time:.
        /// </summary>
        public static string SelectDateTimePrompt {
            get {
                return ResourceManager.GetString("SelectDateTimePrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Hidden.
        /// </summary>
        public static string ShowHidden {
            get {
                return ResourceManager.GetString("ShowHidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set when the first trophy should be earned. All other trophies keep their original spacing..
        /// </summary>
        public static string StartTimeDesc {
            get {
                return ResourceManager.GetString("StartTimeDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Example: if the source's first trophy is Jan 1 2020 and you set start to May 10 2005, all trophies shift back ~15 years while keeping the same gaps between them..
        /// </summary>
        public static string StartTimeExample {
            get {
                return ResourceManager.GetString("StartTimeExample", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Supported: PSN Trophy Leaders, TrueTrophies, PSNProfiles.
        /// </summary>
        public static string SupportedSites {
            get {
                return ResourceManager.GetString("SupportedSites", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add a profile (select a PARAM.SFO file).
        /// </summary>
        public static string TooltipAddProfile {
            get {
                return ResourceManager.GetString("TooltipAddProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+W.
        /// </summary>
        public static string TooltipClose {
            get {
                return ResourceManager.GetString("TooltipClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Support this project.
        /// </summary>
        public static string TooltipDonate {
            get {
                return ResourceManager.GetString("TooltipDonate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Include DST offset when displaying timestamps (only affects trophies earned during DST periods).
        /// </summary>
        public static string TooltipDst {
            get {
                return ResourceManager.GetString("TooltipDst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alt+F4.
        /// </summary>
        public static string TooltipExit {
            get {
                return ResourceManager.GetString("TooltipExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show only bronze trophies.
        /// </summary>
        public static string TooltipFilterBronze {
            get {
                return ResourceManager.GetString("TooltipFilterBronze", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show only earned trophies.
        /// </summary>
        public static string TooltipFilterEarned {
            get {
                return ResourceManager.GetString("TooltipFilterEarned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show only gold trophies.
        /// </summary>
        public static string TooltipFilterGold {
            get {
                return ResourceManager.GetString("TooltipFilterGold", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show only unearned trophies.
        /// </summary>
        public static string TooltipFilterNotEarned {
            get {
                return ResourceManager.GetString("TooltipFilterNotEarned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show only platinum trophies.
        /// </summary>
        public static string TooltipFilterPlatinum {
            get {
                return ResourceManager.GetString("TooltipFilterPlatinum", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show only silver trophies.
        /// </summary>
        public static string TooltipFilterSilver {
            get {
                return ResourceManager.GetString("TooltipFilterSilver", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show only PSN-synced trophies.
        /// </summary>
        public static string TooltipFilterSynced {
            get {
                return ResourceManager.GetString("TooltipFilterSynced", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import timestamps from a trophy website.
        /// </summary>
        public static string TooltipImport {
            get {
                return ResourceManager.GetString("TooltipImport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language: English (more languages coming soon).
        /// </summary>
        public static string TooltipLanguage {
            get {
                return ResourceManager.GetString("TooltipLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More clear options.
        /// </summary>
        public static string TooltipMoreClear {
            get {
                return ResourceManager.GetString("TooltipMoreClear", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More import options.
        /// </summary>
        public static string TooltipMoreImport {
            get {
                return ResourceManager.GetString("TooltipMoreImport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to More unlock options.
        /// </summary>
        public static string TooltipMoreUnlock {
            get {
                return ResourceManager.GetString("TooltipMoreUnlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+O.
        /// </summary>
        public static string TooltipOpen {
            get {
                return ResourceManager.GetString("TooltipOpen", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select a profile to resign trophies to on save. Leave empty for no resigning..
        /// </summary>
        public static string TooltipProfileSelector {
            get {
                return ResourceManager.GetString("TooltipProfileSelector", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove selected profile.
        /// </summary>
        public static string TooltipRemoveProfile {
            get {
                return ResourceManager.GetString("TooltipRemoveProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove from recents.
        /// </summary>
        public static string TooltipRemoveRecent {
            get {
                return ResourceManager.GetString("TooltipRemoveRecent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+S.
        /// </summary>
        public static string TooltipSave {
            get {
                return ResourceManager.GetString("TooltipSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ctrl+F to search.
        /// </summary>
        public static string TooltipSearch {
            get {
                return ResourceManager.GetString("TooltipSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reveal hidden trophy details.
        /// </summary>
        public static string TooltipShowHidden {
            get {
                return ResourceManager.GetString("TooltipShowHidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timezone for trophy timestamps.
        /// </summary>
        public static string TooltipTimezone {
            get {
                return ResourceManager.GetString("TooltipTimezone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unlock all trophies at current time.
        /// </summary>
        public static string TooltipUnlockAll {
            get {
                return ResourceManager.GetString("TooltipUnlockAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} / {1} Trophies.
        /// </summary>
        public static string TrophiesFormat {
            get {
                return ResourceManager.GetString("TrophiesFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Trophy page URL:.
        /// </summary>
        public static string TrophyPageUrl {
            get {
                return ResourceManager.GetString("TrophyPageUrl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User: {0}.
        /// </summary>
        public static string UserFormat {
            get {
                return ResourceManager.GetString("UserFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unlock All.
        /// </summary>
        public static string UnlockAll {
            get {
                return ResourceManager.GetString("UnlockAll", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unlock Selected.
        /// </summary>
        public static string UnlockSelected {
            get {
                return ResourceManager.GetString("UnlockSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Weeks:.
        /// </summary>
        public static string Weeks {
            get {
                return ResourceManager.GetString("Weeks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to With offset.
        /// </summary>
        public static string WithOffset {
            get {
                return ResourceManager.GetString("WithOffset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Years:.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        public static string BrowseTitle {
            get { return ResourceManager.GetString("BrowseTitle", resourceCulture); }
        }

        public static string Select {
            get { return ResourceManager.GetString("Select", resourceCulture); }
        }

        public static string SelectFolder {
            get { return ResourceManager.GetString("SelectFolder", resourceCulture); }
        }

        public static string SelectTrophyFolder {
            get { return ResourceManager.GetString("SelectTrophyFolder", resourceCulture); }
        }

        public static string SelectFile {
            get { return ResourceManager.GetString("SelectFile", resourceCulture); }
        }

        public static string GoUpOneLevel {
            get { return ResourceManager.GetString("GoUpOneLevel", resourceCulture); }
        }

        public static string Refresh {
            get { return ResourceManager.GetString("Refresh", resourceCulture); }
        }

        public static string ThisPC {
            get { return ResourceManager.GetString("ThisPC", resourceCulture); }
        }

        public static string ShowingFiles {
            get { return ResourceManager.GetString("ShowingFiles", resourceCulture); }
        }

        public static string SetTime {
            get { return ResourceManager.GetString("SetTime", resourceCulture); }
        }

        public static string HiddenTrophy {
            get { return ResourceManager.GetString("HiddenTrophy", resourceCulture); }
        }

        public static string HiddenTrophyDesc {
            get { return ResourceManager.GetString("HiddenTrophyDesc", resourceCulture); }
        }

        public static string Unlock {
            get { return ResourceManager.GetString("Unlock", resourceCulture); }
        }

        public static string Lock {
            get { return ResourceManager.GetString("Lock", resourceCulture); }
        }

        public static string SelectedCount {
            get { return ResourceManager.GetString("SelectedCount", resourceCulture); }
        }

        public static string BusyDecrypting {
            get { return ResourceManager.GetString("BusyDecrypting", resourceCulture); }
        }

        public static string BusyEncrypting {
            get { return ResourceManager.GetString("BusyEncrypting", resourceCulture); }
        }

        public static string BusyInitBrowser {
            get { return ResourceManager.GetString("BusyInitBrowser", resourceCulture); }
        }

        public static string BusyFetching {
            get { return ResourceManager.GetString("BusyFetching", resourceCulture); }
        }

        public static string UnsavedChangesConfirm {
            get { return ResourceManager.GetString("UnsavedChangesConfirm", resourceCulture); }
        }

        public static string ErrorOpenFailed {
            get { return ResourceManager.GetString("ErrorOpenFailed", resourceCulture); }
        }

        public static string ErrorSaveFailed {
            get { return ResourceManager.GetString("ErrorSaveFailed", resourceCulture); }
        }

        public static string ErrorAddProfile {
            get { return ResourceManager.GetString("ErrorAddProfile", resourceCulture); }
        }

        public static string ErrorRemoveProfile {
            get { return ResourceManager.GetString("ErrorRemoveProfile", resourceCulture); }
        }

        public static string SelectProfileSFO {
            get { return ResourceManager.GetString("SelectProfileSFO", resourceCulture); }
        }

        public static string EnterProfileName {
            get { return ResourceManager.GetString("EnterProfileName", resourceCulture); }
        }

        public static string AddProfile {
            get { return ResourceManager.GetString("AddProfile", resourceCulture); }
        }

        public static string DefaultProfileName {
            get { return ResourceManager.GetString("DefaultProfileName", resourceCulture); }
        }

        public static string ProfileAdded {
            get { return ResourceManager.GetString("ProfileAdded", resourceCulture); }
        }

        public static string ProfileRemoved {
            get { return ResourceManager.GetString("ProfileRemoved", resourceCulture); }
        }

        public static string RemoveProfileConfirm {
            get { return ResourceManager.GetString("RemoveProfileConfirm", resourceCulture); }
        }

        public static string KeyboardShortcuts {
            get { return ResourceManager.GetString("KeyboardShortcuts", resourceCulture); }
        }

        public static string Hebrew {
            get { return ResourceManager.GetString("Hebrew", resourceCulture); }
        }

        public static string ShortcutsCloseHint {
            get { return ResourceManager.GetString("ShortcutsCloseHint", resourceCulture); }
        }

        public static string ShortcutCatFile {
            get { return ResourceManager.GetString("ShortcutCatFile", resourceCulture); }
        }

        public static string ShortcutCatNavigation {
            get { return ResourceManager.GetString("ShortcutCatNavigation", resourceCulture); }
        }

        public static string ShortcutCatTrophyActions {
            get { return ResourceManager.GetString("ShortcutCatTrophyActions", resourceCulture); }
        }

        public static string ShortcutCatHelp {
            get { return ResourceManager.GetString("ShortcutCatHelp", resourceCulture); }
        }

        public static string ShortcutOpenFolder {
            get { return ResourceManager.GetString("ShortcutOpenFolder", resourceCulture); }
        }

        public static string ShortcutSave {
            get { return ResourceManager.GetString("ShortcutSave", resourceCulture); }
        }

        public static string ShortcutCloseFile {
            get { return ResourceManager.GetString("ShortcutCloseFile", resourceCulture); }
        }

        public static string ShortcutSearch {
            get { return ResourceManager.GetString("ShortcutSearch", resourceCulture); }
        }

        public static string ShortcutEscape {
            get { return ResourceManager.GetString("ShortcutEscape", resourceCulture); }
        }

        public static string ShortcutSelectAll {
            get { return ResourceManager.GetString("ShortcutSelectAll", resourceCulture); }
        }

        public static string ShortcutToggle {
            get { return ResourceManager.GetString("ShortcutToggle", resourceCulture); }
        }

        public static string ShortcutEditTime {
            get { return ResourceManager.GetString("ShortcutEditTime", resourceCulture); }
        }

        public static string ShortcutClearSelected {
            get { return ResourceManager.GetString("ShortcutClearSelected", resourceCulture); }
        }

        public static string ShortcutHelp {
            get { return ResourceManager.GetString("ShortcutHelp", resourceCulture); }
        }

        public static string ErrorPlatinumFailed {
            get { return ResourceManager.GetString("ErrorPlatinumFailed", resourceCulture); }
        }

        public static string ErrorUnlockFailed {
            get { return ResourceManager.GetString("ErrorUnlockFailed", resourceCulture); }
        }

        public static string ErrorImportFailed {
            get { return ResourceManager.GetString("ErrorImportFailed", resourceCulture); }
        }

        public static string ErrorFileImportFailed {
            get { return ResourceManager.GetString("ErrorFileImportFailed", resourceCulture); }
        }

        public static string ConfirmClearNonSynced {
            get { return ResourceManager.GetString("ConfirmClearNonSynced", resourceCulture); }
        }

        public static string ConfirmClearIncludingSynced {
            get { return ResourceManager.GetString("ConfirmClearIncludingSynced", resourceCulture); }
        }

        public static string ConfirmUnlockAll {
            get { return ResourceManager.GetString("ConfirmUnlockAll", resourceCulture); }
        }

        public static string ConfirmClearBatch {
            get { return ResourceManager.GetString("ConfirmClearBatch", resourceCulture); }
        }

        public static string NoTimestampsFound {
            get { return ResourceManager.GetString("NoTimestampsFound", resourceCulture); }
        }

        public static string NoDataFound {
            get { return ResourceManager.GetString("NoDataFound", resourceCulture); }
        }

        public static string ImportedTimestamps {
            get { return ResourceManager.GetString("ImportedTimestamps", resourceCulture); }
        }

        public static string ImportedFromFile {
            get { return ResourceManager.GetString("ImportedFromFile", resourceCulture); }
        }

        public static string UnmatchedSuffix {
            get { return ResourceManager.GetString("UnmatchedSuffix", resourceCulture); }
        }

        public static string UnlockedCount {
            get { return ResourceManager.GetString("UnlockedCount", resourceCulture); }
        }

        public static string LockedCount {
            get { return ResourceManager.GetString("LockedCount", resourceCulture); }
        }

        public static string ClearedCount {
            get { return ResourceManager.GetString("ClearedCount", resourceCulture); }
        }

        public static string CopiedName {
            get { return ResourceManager.GetString("CopiedName", resourceCulture); }
        }

        public static string FolderNoLongerExists {
            get { return ResourceManager.GetString("FolderNoLongerExists", resourceCulture); }
        }

        public static string SyncedCannotClear {
            get { return ResourceManager.GetString("SyncedCannotClear", resourceCulture); }
        }

        public static string SelectTrophyImportFile {
            get { return ResourceManager.GetString("SelectTrophyImportFile", resourceCulture); }
        }

        public static string ImportFormatHint {
            get { return ResourceManager.GetString("ImportFormatHint", resourceCulture); }
        }

        public static string NoValidTimestampsInFile {
            get { return ResourceManager.GetString("NoValidTimestampsInFile", resourceCulture); }
        }

        public static string ImportComplete {
            get { return ResourceManager.GetString("ImportComplete", resourceCulture); }
        }

        public static string ImportCompleteMessage {
            get { return ResourceManager.GetString("ImportCompleteMessage", resourceCulture); }
        }
    }
}
